spring:
  zipkin:
    base-url: http://zipkin:9411
  kafka:
    bootstrap-servers: broker:29092
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka