spring:
  application:
    name: notification-service

  zipkin:
    base-url: http://localhost:9411

  sleuth:
    probability: 1.0

  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      ## deserialize notification key
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      ## deserialize notification value (java object) to json object
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: notificationId
      properties:
        spring:
          json:
            type:
              mapping: event:org.mvc.event.OrderPlacedEvent


server:
  port: 8088

# Actuators properties
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always