## add eureka server url to this client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        ## Product Service Route
        - id: product-service
          uri: lb://product-service # used lb to allow client side to do some load balancing
          predicates:
            - Path= /api/product

        ## Order Service Route
        - id: order-service
          uri: lb://order-service # used lb to allow client side to do some load balancing
          predicates:
            - Path= /api/order

        ## Discovery Server Route
        - id: discovery-service
          uri: http://localhost:8761 # used lb to allow client side to do some load balancing
          predicates:
            - Path= /eureka/web
          filters:
            - SetPath= /
        ## Discovery Server static resource Route
        - id: discovery-service
          uri: http://localhost:8761 # used lb to allow client side to do some load balancing
          predicates:
            - Path= /eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/project-mvc

  zipkin:
    base-url: http://localhost:9411

  sleuth:
    probability: 1.0
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
#            route:
#              RouteDefinitionRouteLocator: INFO
#            nodeValue: TRACE
    ## ROOT LOGGER OF THE WHOLE APPLICATION
    root: INFO


# Actuators properties
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always


