spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ptechie
    url: jdbc:postgresql://postgres:5431/order-service
    password: password
  zipkin:
    base-url: http://zipkin:9411
  kafka:
    bootstrap-servers: broker:29092
server:
  port: '8080'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
