
spring:
  #  profiles:
  #    active: @activatedProperties@
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/orderservice
    username: postgres
    password: andela

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka