
spring:
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/product'

  application:
    name: product-service

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
