spring:
  zipkin:
    base-url: http://zipkin:9411
  data:
    mongodb:
      database: product-service
      port: '27017'
      host: mongo
server:
  port: '8080'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
